export const ADD_CATEGORY = 'ADD_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const ADD_LOCATION = 'ADD_LOCATION'
export const UPDATE_LOCATION = 'UPDATE_LOCATION'
export const DELETE_LOCATION = 'DELETE_LOCATION'